export enum GetTodosActionTypes {
  GET_TODOS_REQUEST = 'GET_TODOS_REQUEST',
  GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS',
  GET_TODOS_FAIL = 'GET_TODOS_FAIL',
  GET_TODOS_RESET = 'GET_TODOS_RESET',
}

export enum GetTodoActionTypes {
  GET_TODO_REQUEST = 'GET_TODO_REQUEST',
  GET_TODO_SUCCESS = 'GET_TODO_SUCCESS',
  GET_TODO_FAIL = 'GET_TODO_FAIL',
  GET_TODO_RESET = 'GET_TODO_RESET',
}